name: synheart_emotion
description: On-device emotion inference from biosignals (HR/RR) for Flutter applications
version: 0.1.0
homepage: https://github.com/synheart-ai/synheart-emotion
repository: https://github.com/synheart-ai/synheart-emotion

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_onnxruntime: ^1.5.2
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
