name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy models to Flutter assets
        run: |
          mkdir -p sdks/flutter/assets/ml
          cp models/*.json sdks/flutter/assets/ml/ 2>/dev/null || echo "⚠️ No models to copy"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        working-directory: sdks/flutter
        run: flutter pub get

      - name: Verify formatting
        working-directory: sdks/flutter
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze code
        working-directory: sdks/flutter
        run: flutter analyze

      - name: Check for outdated dependencies
        working-directory: sdks/flutter
        run: flutter pub outdated

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy models to Flutter assets
        run: |
          mkdir -p sdks/flutter/assets/ml
          cp models/*.json sdks/flutter/assets/ml/ 2>/dev/null || echo "⚠️ No models to copy"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        working-directory: sdks/flutter
        run: flutter pub get

      - name: Run unit tests
        working-directory: sdks/flutter
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./sdks/flutter/coverage/lcov.info
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

  test-multiplatform:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        flutter-version: ['3.10.0', '3.24.0']
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy models to Flutter assets
        run: |
          mkdir -p sdks/flutter/assets/ml
          cp models/*.json sdks/flutter/assets/ml/ 2>/dev/null || echo "⚠️ No models to copy"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: 'stable'
          cache: true

      - name: Install dependencies
        working-directory: sdks/flutter
        run: flutter pub get

      - name: Run tests
        working-directory: sdks/flutter
        run: flutter test

  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        working-directory: sdks/flutter
        run: flutter pub get

      - name: Run benchmark tests
        working-directory: sdks/flutter
        run: flutter test test/benchmarks_test.dart

      - name: Save benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: sdks/flutter/test/benchmarks_test.dart
          retention-days: 30

  package-score:
    name: Check Package Score
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        working-directory: sdks/flutter
        run: flutter pub get

      - name: Install pana
        run: flutter pub global activate pana

      - name: Run pana analysis
        working-directory: sdks/flutter
        run: flutter pub global run pana --no-warning --exit-code-threshold 0

  build-example:
    name: Build Example App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies (Flutter SDK)
        working-directory: sdks/flutter
        run: flutter pub get

      - name: Install dependencies (example)
        working-directory: examples
        run: flutter pub get

      - name: Build example app (Android)
        working-directory: examples
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: example-app-debug
          path: examples/build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7

  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        working-directory: sdks/flutter
        run: flutter pub get

      - name: Check for known security vulnerabilities
        working-directory: sdks/flutter
        run: |
          flutter pub outdated --mode=null-safety
          echo "Manual security review recommended"

  all-checks-passed:
    name: All Checks Passed
    needs: [analyze, test, test-multiplatform]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Check all job results
        run: |
          if [ "${{ needs.analyze.result }}" != "success" ] || \
             [ "${{ needs.test.result }}" != "success" ] || \
             [ "${{ needs.test-multiplatform.result }}" != "success" ]; then
            echo "Some required checks failed"
            exit 1
          fi
          echo "All required checks passed!"
